var dbb = {
	BUILDING: 'building',
	USER: 'user',
	UNIT: 'unit',
	HOMEINFO: 'homeinfo',
	UNITTYPE: 'unit_type',
	VENDOR: 'vendor',
	ENOTICE: 'enotice',
	RESIDENT: 'resident',
	DEPARTMENT: 'department',
	EMPLOYEE: 'employee',
	HELPER: 'helper',
	IDPROOF: 'idproof',
	VEHICLE: 'vehicle',
	AMENITIES: 'amenities',
	AMENITIESBOOKING: 'amenitiesbooking',
	COMPLAINTS: 'complaints',
	VISITORS: 'visitors',
	UNITHELPER: 'unit_helper',
	SHARINGWALL: 'sharing_wall',
	CLASSIFIED: 'classified',
	VENDORCATEGORIES: 'vendorcategories',
	HELPER_VISITORS: "helper_visitors",
	EMPLOYEE_VISITORS: "employee_visitors",
	RESIDENT_ENTRIES: "resident_entries",
	VENDOR_ENTRIES: "vendor_entries",
	SOS: "sos",
	POLLING: "polling",
	UNIT_MAINTENANCE: "unit_maintenance",
	MAINTENANCE_TYPE: "maintenance_types",
	BANKACCOUNT_ROLES: "bankaccount_role",
	ASSET_TYPES: "asset_types",
	ASSET: "asset",
	SALARY: "salary",
	LOANS: "loans",
	LOAN_EMI: "loan_emi",
	LEGAL: "legal",
};

module.exports = dbb